---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seatsurfing.fullname" . }}
stringData:
  {{- if and (not .Values.seatsurfing.postgresql.password.existingSecret) (not .Values.seatsurfing.postgresql.connectionString.existingSecret) }}
  POSTGRES_PASS: {{ .Values.seatsurfing.postgresql.password.value }}
  {{- end }}
  {{- if not .Values.seatsurfing.cryptKey.existingSecret }}
  CRYPT_KEY: "{{ .Values.seatsurfing.cryptKey.value }}"
  {{- end }}
  {{- if and .Values.seatsurfing.smtp.enabled (eq .Values.seatsurfing.smtp.auth "1") (not .Values.seatsurfing.smtp.password.existingSecret) }}
  SMTP_AUTH_PASS: "{{ .Values.seatsurfing.smtp.password.value }}"
  {{- end }}
